// =============================================================================
// YemenChat - Firebase Options
// =============================================================================
// Firebase configuration - requires setup with FlutterFire CLI.
// Run: flutterfire configure
// This file will be auto-generated by the FlutterFire CLI.
// =============================================================================

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration options.
///
/// IMPORTANT: This is a placeholder file. You need to configure Firebase for
/// your project by running:
///
/// ```bash
/// dart pub global activate flutterfire_cli
/// flutterfire configure
/// ```
///
/// This will create the proper firebase_options.dart file with your project's
/// configuration. The configuration below contains placeholder values that
/// MUST be replaced with your actual Firebase project settings.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ============================================================================
  // PLACEHOLDER VALUES - Replace with your Firebase project configuration
  // Run: flutterfire configure
  // ============================================================================

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoXhxiSL68QvLrclDbfvWxwJk5b_UhlRc',
    appId: '1:55093432147:web:e31e300c5ba13664391ba6',
    messagingSenderId: '55093432147',
    projectId: 'yemenchat-18235',
    authDomain: 'yemenchat-18235.firebaseapp.com',
    storageBucket: 'yemenchat-18235.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWosxBjmVMLmkJ65XjkPqLSTXYi6jA-1o',
    appId: '1:55093432147:android:df15914fa27a5445391ba6',
    messagingSenderId: '55093432147',
    projectId: 'yemenchat-18235',
    storageBucket: 'yemenchat-18235.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAWmaEiUN9i5xR2vq1Y50VhLHteRxnMcw',
    appId: '1:55093432147:ios:38f2dbb544497dfd391ba6',
    messagingSenderId: '55093432147',
    projectId: 'yemenchat-18235',
    storageBucket: 'yemenchat-18235.firebasestorage.app',
    iosBundleId: 'com.example.yemenchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAWmaEiUN9i5xR2vq1Y50VhLHteRxnMcw',
    appId: '1:55093432147:ios:38f2dbb544497dfd391ba6',
    messagingSenderId: '55093432147',
    projectId: 'yemenchat-18235',
    storageBucket: 'yemenchat-18235.firebasestorage.app',
    iosBundleId: 'com.example.yemenchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoXhxiSL68QvLrclDbfvWxwJk5b_UhlRc',
    appId: '1:55093432147:web:cf0934e4cadaaa59391ba6',
    messagingSenderId: '55093432147',
    projectId: 'yemenchat-18235',
    authDomain: 'yemenchat-18235.firebaseapp.com',
    storageBucket: 'yemenchat-18235.firebasestorage.app',
  );

}